version: "3"
services: 
  shoot-backend:
    container_name: "shoot-backend"
    build:
      context: "./backend/ShootTheMoon"
      dockerfile: "ShootTheMoon/Dockerfile"
    ports: 
      - "8000:80"
    environment:
      ENABLE_SWAGGER: "true"
  shoot-frontend:
    container_name: "shoot-frontend"
    build:
        context: "./frontend/shoot-client"
        dockerfile: Dockerfile
    ports:
      - "8001:80"
